
services:
  stats-server:
    build: stats/stats-server
    image: stats/stats-server
    container_name: statsApp
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsDb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass

  stats-db:
    image: postgres:16.1
    container_name: statsDb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/statDb:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statsDb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass

  ewm-service:
    build: main-service
    image: main-service
    container_name: mainService
    ports:
      - "8080:8080"
    depends_on:
      - main-db

  main-db:
      image: postgres:16.1
      container_name: mainDb
      ports:
        - "5433:5432"
      volumes:
        - ./volumes/mainDb:/var/lib/postgresql/data/

      environment:
        - POSTGRES_DB=mainDb
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=dbpass
